source "https://rubygems.org"
gem "minimal-mistakes-jekyll"
gem "webrick", "~> 1.7"
gem "jekyll", "~> 4.2"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "jekyll-feed"
gem "jekyll-include-cache"
gem "kramdown-parser-gfm"
gem 'jekyll-algolia'